# example netlify.toml
[build]
  command = "yarn run build"
  functions = "functions" #  netlify-lambda reads this
  publish = "public"


# # COMMENT: This a rule for Single Page Applications
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

## more info https://www.netlify.com/docs/netlify-toml-reference/
